version: '3.2'
services:
  postgres:
    image: postgres:12
    container_name: bewiseai_postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - '7777:5432'
    volumes:
      - ./db/:/var/lib/postgresql/data

  app:
    build: app/
    container_name: bewiseai_v1
    depends_on:
      - postgres
    ports:
      - '7070:7070'
    volumes:
      - ./app:/app